version: '3.8'

services:
  app:
    build: .
    container_name: notejam_app
    ports:
      - "3000:3000"
    environment:
      # Environment variables for the app
      - NODE_ENV=development
      # DATABASE_URL must match the DSN in settings.js
      - DATABASE_URL=postgres://notejam:notejam@db:5432/notejam
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: notejam_db
    environment:
      - POSTGRES_USER=notejam
      - POSTGRES_PASSWORD=notejam
      - POSTGRES_DB=notejam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
